version: '3'
networks:
  rust-server:
    name: rust-server
services:
  db:
    image: postgres:10.8
    ports:
      - "5432:5432"
    restart: always
    networks:
      - rust-server
    volumes: 
      - pgdata:/var/lib/postgresql/data
  server:
    image: rust-server:dev
    build:
      context: ../../
      dockerfile: Dockerfile.local
    restart: always
    command: 
      - /bin/bash
      - -c
      - |
        ./wait-for-it.sh db:5432
        cargo watch -x run --debug
    ports:
      - "8000:8000"
    environment:
      - SERVER_URL
      - DATABASE_URL
    volumes:
      - /app/target
    depends_on:
      - db
    networks:
      - rust-server
volumes:
  pgdata:
