version: '3'
networks:
  rust-server:
    name: rust-server
services:
  db:
    image: postgres:10.8
    ports:
      - "5432:5432"
    restart: always
    networks:
      - rust-server
    volumes: 
      - pgdata:/var/lib/postgresql/data
  server:
    image: rust-server:dev
    build:
      context: ../../
      dockerfile: Dockerfile.local
      target: dev
    restart: always
    command: 
      - /bin/bash
      - -c
      - |
        cargo watch --debug -q  -x run 
    ports:
      - "8000:8000"
    environment:
      - SERVER_URL=0.0.0.0:8000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ../..:/app
      - /app/target
    depends_on:
      - db
    networks:
      - rust-server
volumes:
  pgdata:
